name: 'Cache Result'
description: 'Github Action for storing results from previous runs by SHA'
inputs:
  result:
    description: 'The most recent result to store'
    required: true
    default: 'unknown'
  token:
    description: 'GitHub token for GitHub API requests'
    required: true
    default: ${{ github.token }}
  cache-group:
    description: >
      A string that will be added to the cache key when storing a result.
      Defaults to the name of the workflow using the action.
    required: true
    default: ${{ github.workflow }}
outputs:
  result:
    description: 'Most recent result'
runs:
  using: 'node16'
  main: 'dist/index.js'
