name: 'SHA Storage'
description: 'Github Action for storing results from previous runs by SHA'
inputs:
  result:
    description: 'The most recent result to store'
    required: true
    default: 'unknown'
  token:
    description: >
      GitHub token for GitHub API requests.
      When `repository` is modified, set to a personal access token with access to `repository`.
    required: true
    default: ${{ github.token }}
outputs:
  result:
    description: 'Most recent result'
  deploy_sha:
    description: 'The current SHA of the default branch of the repo.'
runs:
  using: 'node16'
  main: 'src/index.js'
