name: "Cache Result"
description: "Github Action for storing results from previous runs by SHA"
inputs:
  result:
    description: "The most recent result to store"
    required: true
    default: "unknown"
  cache-group:
    description: >
      A string that will be added to the cache key when storing a result.
      Defaults to the name of the workflow using the action.
    required: true
    default: ${{ github.workflow }}
outputs:
  result:
    description: "Most recent result"
runs:
  using: "node20"
  main: "dist/index.js"
