name: 'Cache Result'
description: 'Github Action for storing results from previous runs by SHA'
inputs:
  result:
    description: 'The most recent result to store'
    required: true
    default: 'unknown'
  token:
    description: 'GitHub token for GitHub API requests'
    required: true
    default: ${{ github.token }}
  key-prefix:
    description: 'A string that will be added to the cache key when storing a result.'
    required: false
outputs:
  result:
    description: 'Most recent result'
  deploy_sha:
    description: 'The current SHA of the default branch of the repo.'
runs:
  using: 'node16'
  main: 'dist/index.js'
