name: ci
on: push

env:
  NODE_VERSION: 24.14.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install deps and build dist
        run: npm i

      - name: Check for unexpected dist changes
        run: git diff --quiet

      - run: npm run lint
