name: run-cache-result-action
on: push

jobs:
  check-sha-result:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.restore-cache.outputs.result }}
      optional-result: ${{ steps.restore-secondary-cache.outputs.result }}
    steps:
      - id: restore-cache
        uses: parallel-markets/cache-result-action@bc6ad0498f85ba42e2ac6d523c69ee245e8cbbf5

      - id: restore-secondary-cache
        uses: parallel-markets/cache-result-action@bc6ad0498f85ba42e2ac6d523c69ee245e8cbbf5
        with:
          cache-group: optional

  test:
    needs: check-sha-result
    runs-on: ubuntu-latest
    steps:
      - uses: parallel-markets/cache-result-action@bc6ad0498f85ba42e2ac6d523c69ee245e8cbbf5
        with:
          result: success

  optional-test:
    needs: check-sha-result
    runs-on: ubuntu-latest
    steps:
      - uses: parallel-markets/cache-result-action@bc6ad0498f85ba42e2ac6d523c69ee245e8cbbf5
        with:
          result: success
          cache-group: optional
