name: run-cache-result-action
on: push

jobs:
  check-sha-result:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.restore-cache.outputs.result }}
      optional-result: ${{ steps.restore-secondary-cache.outputs.result }}
    steps:
      - id: restore-cache
        uses: parallel-markets/cache-result-action@4db5b44234b8debe522518ec304be376706478f8

      - id: restore-secondary-cache
        uses: parallel-markets/cache-result-action@4db5b44234b8debe522518ec304be376706478f8
        with:
          cache-group: optional

  test:
    needs: check-sha-result
    runs-on: ubuntu-latest
    steps:
      - uses: parallel-markets/cache-result-action@4db5b44234b8debe522518ec304be376706478f8
        with:
          result: success

  optional-test:
    needs: check-sha-result
    runs-on: ubuntu-latest
    steps:
      - uses: parallel-markets/cache-result-action@4db5b44234b8debe522518ec304be376706478f8
        with:
          result: success
          cache-group: optional
