name: run-cache-result-action
on: push

jobs:
  check-sha-result:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.restore-cache.outputs.result }}
      optional-result: ${{ steps.restore-secondary-cache.outputs.result }}
    steps:
      - id: restore-cache
        uses: parallel-markets/cache-result-action@a1e2c3ccc1be6464c4d571ff2932d6b6c9ae3e3d

      - id: restore-secondary-cache
        uses: parallel-markets/cache-result-action@a1e2c3ccc1be6464c4d571ff2932d6b6c9ae3e3d
        with:
          cache-group: optional

  test:
    needs: check-sha-result
    runs-on: ubuntu-latest
    steps:
      - uses: parallel-markets/cache-result-action@a1e2c3ccc1be6464c4d571ff2932d6b6c9ae3e3d
        with:
          result: success

  optional-test:
    needs: check-sha-result
    runs-on: ubuntu-latest
    steps:
      - uses: parallel-markets/cache-result-action@a1e2c3ccc1be6464c4d571ff2932d6b6c9ae3e3d
        with:
          result: success
          cache-group: optional
