name: run-cache-result-action
on: push

# tag: `edge` should point to master or a branch commit to verify
# that a change is valid before merging.

# To update edge to the current commit, use:
# $ git tag -f edge HEAD && git push -f origin edge

jobs:
  check-sha-result:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.restore-cache.outputs.result }}
      optional-result: ${{ steps.restore-secondary-cache.outputs.result }}
    steps:
      - id: restore-cache
        uses: parallel-markets/cache-result-action@edge

      - id: restore-secondary-cache
        uses: parallel-markets/cache-result-action@edge
        with:
          cache-group: optional

  test:
    needs: check-sha-result
    runs-on: ubuntu-latest
    steps:
      - uses: parallel-markets/cache-result-action@edge
        with:
          result: success

  optional-test:
    needs: check-sha-result
    runs-on: ubuntu-latest
    steps:
      - uses: parallel-markets/cache-result-action@edge
        with:
          result: success
          cache-group: optional
