name: run-cache-result-action
on: push

jobs:
  check-sha-result:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.restore-cache.outputs.result }}
      optional-result: ${{ steps.restore-secondary-cache.outputs.result }}
    steps:
      - id: restore-cache
        uses: parallel-markets/cache-result-action@f6b4cbf83108f6b777dfc78925e71da352189d05

      - id: restore-secondary-cache
        uses: parallel-markets/cache-result-action@f6b4cbf83108f6b777dfc78925e71da352189d05
        with:
          cache-group: optional

  test:
    needs: check-sha-result
    runs-on: ubuntu-latest
    steps:
      - uses: parallel-markets/cache-result-action@f6b4cbf83108f6b777dfc78925e71da352189d05
        with:
          result: success

  optional-test:
    needs: check-sha-result
    runs-on: ubuntu-latest
    steps:
      - uses: parallel-markets/cache-result-action@f6b4cbf83108f6b777dfc78925e71da352189d05
        with:
          result: success
          cache-group: optional
