name: run-cache-result-action
on: push

jobs:
  check-sha-result:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.restore-cache.outputs.result }}
      optional-result: ${{ steps.restore-secondary-cache.outputs.result }}
    steps:
      - id: restore-cache
        uses: parallel-markets/cache-result-action@081f941880f769d9b3fdcf63c97ff4d4f57d8840

      - id: restore-secondary-cache
        uses: parallel-markets/cache-result-action@081f941880f769d9b3fdcf63c97ff4d4f57d8840
        with:
          cache-group: optional

  test:
    needs: check-sha-result
    runs-on: ubuntu-latest
    steps:
      - uses: parallel-markets/cache-result-action@081f941880f769d9b3fdcf63c97ff4d4f57d8840
        with:
          result: success

  optional-test:
    needs: check-sha-result
    runs-on: ubuntu-latest
    steps:
      - uses: parallel-markets/cache-result-action@081f941880f769d9b3fdcf63c97ff4d4f57d8840
        with:
          result: success
          cache-group: optional
